### PR TITLE
Update 1-polkadot-token-standard.md

### PR DESCRIPTION
**Pull request by pserg1**
Initital proposition taken from [this google doc](https://docs.google.com/document/d/1ldwXi_UYfvhFnLrxx6wMZztfMe8LYMsgcf_0hqYJ1Jg/edit#)

### CODE REVIEW

**Comment by BenWhiteJam** [comment]
Hi @pserg1,
thank you very much for the PR and for taking the polkadot token standard initiative.
Would be great if you could update two points:
1. You and Ben would ben the `Champions` -> spear heading the working group and making sure regular discussions and information exchange will happen. Teams who are interested or taking part in the definition of the token standards should get listed/added to `Contributors`
2. Please move the 1-polkadot-token-standard.md to the root path of the repo for now
(I'll update both things in the general readme and describe it in a better way than it is right now)

**Comment by pserg1** [comment]
> Hi @pserg1,
> thank you very much for the PR and for taking the polkadot token standard initiative.
> Would be great if you could update two points:
> 
> 1. You and Ben would ben the `Champions` -> spear heading the working group and making sure regular discussions and information exchange will happen. Teams who are interested or taking part in the definition of the token standards should get listed/added to `Contributors`
> 2. Please move the 1-polkadot-token-standard.md to the root path of the repo for now
> 
> (I'll update both things in the general readme and describe it in a better way than it is right now)

**Comment by pserg1** [comment]
> > Hi @pserg1,
> > thank you very much for the PR and for taking the polkadot token standard initiative.
> > Would be great if you could update two points:
> > 
> > 1. You and Ben would ben the `Champions` -> spear heading the working group and making sure regular discussions and information exchange will happen. Teams who are interested or taking part in the definition of the token standards should get listed/added to `Contributors`
> > 2. Please move the 1-polkadot-token-standard.md to the root path of the repo for now
> > 
> > (I'll update both things in the general readme and describe it in a better way than it is right now)

Hi, @BenWhiteJam 

1. I did the first one: Me and Ben are champions, people who actually talked to us are contributors now (Don't know emails or github acc's of Nate and Jakub, though ,we've used Telegram to chat) 

2. I don't know how to do this when editing a pr.

**Review by BenWhiteJam — APPROVED** [review]
👍

**Pull request merged**
